[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32F767ZITx --defmt"
rustflags = [
  "-C", "linker=rust-lld",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[alias]
rb = "run --bin"
rrb = "run --release --bin"